framework:
    messenger:
        # Set command bus as default
        default_bus: command.bus
        
        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
            
            query.bus:
                default_middleware: allow_no_handlers