# Nelmio API Doc routes
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: 'nelmio_api_doc.controller.redocly' }

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: 'nelmio_api_doc.controller.swagger_json' }