# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Infrastructure\Http\Controller\:
        resource: '../src/Infrastructure/Http/Controller'
        tags: ['controller.service_arguments']
        public: true
    

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Bus implementations
    App\Shared\Application\CommandBus: '@App\Infrastructure\Bus\SymfonyCommandBus'
    App\Shared\Application\QueryBus: '@App\Infrastructure\Bus\SymfonyQueryBus'
    
    # Command Bus configuration
    App\Infrastructure\Bus\SymfonyCommandBus:
        arguments:
            $commandBus: '@command.bus'
    
    # Query Bus configuration
    App\Infrastructure\Bus\SymfonyQueryBus:
        arguments:
            $queryBus: '@query.bus'
    
    # Command Handlers
    App\Project\Application\Command\:
        resource: '../src/Project/Application/Command/*Handler.php'
        tags:
            - { name: messenger.message_handler, bus: command.bus }
    
    App\User\Application\Command\:
        resource: '../src/User/Application/Command/*Handler.php'
        tags:
            - { name: messenger.message_handler, bus: command.bus }
    
    # Query Handlers
    App\Project\Application\Query\:
        resource: '../src/Project/Application/Query/*Handler.php'
        tags:
            - { name: messenger.message_handler, bus: query.bus }
            
    App\User\Application\Query\:
        resource: '../src/User/Application/Query/*Handler.php'
        tags:
            - { name: messenger.message_handler, bus: query.bus }
            
    # Cross-Domain Query Handlers
    App\Shared\Application\CrossDomain\Query\:
        resource: '../src/Shared/Application/CrossDomain/Query/*Handler.php'
        tags:
            - { name: messenger.message_handler, bus: query.bus }

    # Event Handlers for domain events
    App\Shared\Application\EventHandler\UserDeletedEventHandler:
        tags:
            - { name: kernel.event_listener, event: 'App\User\Domain\Event\UserDeletedEvent' }
    
    # Project Event Handlers for read model projection and side effects
    App\Project\Application\EventHandler\ProjectEventHandler:
        tags:
            - { name: kernel.event_listener, event: 'App\Project\Domain\Event\ProjectCreatedEvent' }
            - { name: kernel.event_listener, event: 'App\Project\Domain\Event\ProjectRenamedEvent' }
            - { name: kernel.event_listener, event: 'App\Project\Domain\Event\ProjectDeletedEvent' }
            - { name: kernel.event_listener, event: 'App\Project\Domain\Event\ProjectWorkerAddedEvent' }
            - { name: kernel.event_listener, event: 'App\Project\Domain\Event\ProjectWorkerRemovedEvent' }

    # Event Serializers
    App\Project\Infrastructure\Event\ProjectEventSerializer: ~
    App\User\Infrastructure\Event\UserEventSerializer: ~

    App\Infrastructure\Event\CompositeEventSerializer:
        arguments:
            - '@App\Project\Infrastructure\Event\ProjectEventSerializer'
            - '@App\User\Infrastructure\Event\UserEventSerializer'

    App\Shared\Event\EventSerializer: '@App\Infrastructure\Event\CompositeEventSerializer'
    App\Shared\Event\EventDispatcher: '@App\Shared\Infrastructure\Event\DomainEventDispatcher'
    App\Shared\Event\EventStore: '@App\Infrastructure\Persistence\EventStore\DoctrineEventStore'
    App\Project\Domain\Repository\ProjectRepositoryInterface: '@App\Infrastructure\Persistence\EventStore\ProjectEventStoreRepository'
    
    # Snapshot components
    App\Shared\Event\SnapshotStore: '@App\Infrastructure\Persistence\Snapshot\DoctrineSnapshotStore'
    App\Shared\Event\SnapshotStrategy: '@App\Infrastructure\Event\FrequencyBasedSnapshotStrategy'
    
    App\Infrastructure\Persistence\Snapshot\DoctrineSnapshotStore:
        arguments:
            $connection: '@doctrine.dbal.default_connection'
    
    App\Infrastructure\Event\FrequencyBasedSnapshotStrategy:
        arguments:
            $snapshotFrequency: 10  # Create snapshot every 10 events
    
    App\Project\Domain\Model\ProjectSnapshotFactory: ~
    
    # Read Model Repository
    App\Project\Infrastructure\Persistence\ReadModel\ProjectReadModelRepository: ~
    
    # Read Model Projection
    App\Project\Infrastructure\Projection\ProjectReadModelProjection: ~
    
    # Optimized Query Handlers
    App\Project\Application\Query\FindProjectsByOwnerOptimizedHandler:
        tags:
            - { name: messenger.message_handler, bus: query.bus }
    
    # Interface bindings
    App\Infrastructure\Http\Mapper\ProjectDtoMapperInterface: '@App\Infrastructure\Http\Mapper\ProjectDtoMapper'
    
    # Domain Event Dispatcher
    App\Shared\Infrastructure\Event\DomainEventDispatcher: ~
